server_config_path = "server.toml"

[storage]
type = "inline"
root = "/home/phyxdown/nephele/image/"

#path = "oss.so"
#endpoint = "[endpoint]"
#bucketname = "[bucketname]"
#accessKeyId = "[access-key-id]"
#accessKeySecret = "[access-key-secret]"

[interpret]
type = "inline"
